// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketParcial.Infrastructure;

namespace TicketParcial.Migrations.TicketTurno
{
    [DbContext(typeof(TicketTurnoContext))]
    [Migration("20220405003002_modelos ticket")]
    partial class modelosticket
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketParcial.Models.AsuntoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AsuntosList");
                });

            modelBuilder.Entity("TicketParcial.Models.MunicipioModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MunicipiosList");
                });

            modelBuilder.Entity("TicketParcial.Models.NivelModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NivelesList");
                });

            modelBuilder.Entity("TicketParcial.Models.TicketTurnoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("asuntoID")
                        .HasColumnType("int");

                    b.Property<int>("celular")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("curp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("materno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("municipioID")
                        .HasColumnType("int");

                    b.Property<int?>("nivelID")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreRealiza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("telefono")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("asuntoID");

                    b.HasIndex("municipioID");

                    b.HasIndex("nivelID");

                    b.ToTable("TicketTurnoList");
                });

            modelBuilder.Entity("TicketParcial.Models.TicketTurnoModel", b =>
                {
                    b.HasOne("TicketParcial.Models.AsuntoModel", "asunto")
                        .WithMany("ticketList")
                        .HasForeignKey("asuntoID");

                    b.HasOne("TicketParcial.Models.MunicipioModel", "municipio")
                        .WithMany("ticketList")
                        .HasForeignKey("municipioID");

                    b.HasOne("TicketParcial.Models.NivelModel", "nivel")
                        .WithMany("ticketList")
                        .HasForeignKey("nivelID");
                });
#pragma warning restore 612, 618
        }
    }
}
